sync with etobi's Debian packages

diff --git a/debian/vdr.postinst b/debian/vdr.postinst
--- a/debian/vdr.postinst
+++ b/debian/vdr.postinst
@@ -1,77 +1,146 @@
-#!/bin/sh
-
-# Peter Siering <ps@ctmagazin.de>, 10/2/2003
-
-ACTION=$1
-
-# Upgrade <= 1.2.6-26 to a more FHS-conform directory structure
+#! /bin/sh
+# postinst script for vdr
 #
+# see: dh_installdeb(1)
 
-if [ "$ACTION" = "configure" ] ; then
-    # Fix channels.conf when updating from 1.5.14 to 1.5.15
-    if dpkg --compare-versions "$2" ge "1.5.14" ; then
-        if dpkg --compare-versions "$2" lt "1.5.15" ; then
-            if [ -e /var/lib/vdr/channels.conf ]; then
-                cp /var/lib/vdr/channels.conf /var/lib/vdr/channels.conf.1.5.14
-                sed -i 's/M2O0S0//' /var/lib/vdr/channels.conf
-            fi
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+#
+# quoting from the policy:
+#     Any necessary prompting should almost always be confined to the
+#     post-installation script, and should be protected with a conditional
+#     so that unnecessary prompting doesn't happen if a package's
+#     installation fails and the `postinst' is called with `abort-upgrade',
+#     `abort-remove' or `abort-deconfigure'.
+
+# source debconf lib
+#. /usr/share/debconf/confmodule
+
+case "$1" in
+    configure)
+
+        . /usr/share/debconf/confmodule
+
+        # install/move channels.conf 
+        if [ ! -e /var/lib/vdr/channels.conf ]; then
+                db_get vdr/select_dvb_card
+
+                case "$RET" in
+                Satellite)
+                        gzip -dc /usr/share/doc/vdr/examples/channels.conf.gz \
+                        > /var/lib/vdr/channels.conf
+                        chmod 644 /var/lib/vdr/channels.conf
+                ;;
+                Terrestrial)
+                        gzip -dc /usr/share/doc/vdr/examples/channels.conf.terr.gz \
+                        > /var/lib/vdr/channels.conf
+                        chmod 644 /var/lib/vdr/channels.conf
+                ;;
+                Cable)
+                        gzip -dc /usr/share/doc/vdr/examples/channels.conf.cable.gz \
+                        > /var/lib/vdr/channels.conf
+                        chmod 644 /var/lib/vdr/channels.conf
+                ;;
+                esac
         fi
-    fi
 
-    [ ! -d /var/lib/video.00 ] && mkdir /var/lib/video.00
+        db_get vdr/create_video_dir
+        if $RET; then
+                # check if an old directory /var/lib/video exists, and 
+                # symlink it to /var/lib/video.00
+                if [ -d /var/lib/video ] && [ ! -e /var/lib/video.00 ]; then
+                        ln -s video /var/lib/video.00
+                fi
 
-    # copy example channels.conf files into config dir
-    if [ ! -e /var/lib/vdr/channels.conf ]; then
-        cp /usr/share/doc/vdr/examples/channels.conf* /var/lib/vdr/
-        gunzip /var/lib/vdr/channels.conf*.gz
-    fi
+                # create /var/lib/video.00 if it does not exist
+                if [ ! -e /var/lib/video.00 ]; then
+                        mkdir /var/lib/video.00
+                fi
 
-    # ensure that user and group 'vdr' exist
-    USER=vdr
-    GROUP=vdr
-    if ! getent group | grep -q "^$GROUP:" ; then
-        echo -n "Adding group $GROUP.."
-        addgroup --quiet --gid 666 --system $GROUP
-        echo "..done"
-    fi
-    if ! getent passwd | grep -q "^$USER:"; then
-        echo -n "Adding user $USER.."
-        adduser --system --uid 666 --home /var/lib/vdr --shell /bin/false \
-          --gecos "VDR user" --no-create-home \
-          --disabled-login --disabled-password \
-          --ingroup $GROUP \
-          $USER
-        echo "...done"
-    fi
+                # check if /var/lib/video.00 exists and /var/lib/video is 
+                # missing, then create the symlink /var/lib/video which
+                # points to /var/lib/video.00
+                if [ ! -e /var/lib/video ] && [ -e /var/lib/video.00 ]; then
+                        ln -s video.00 /var/lib/video
+                fi
+        fi
 
-    # put vdr in group video so that it can access the DVB device nodes
-    adduser $USER video > /dev/null || true
+        # ensure that user and group 'vdr' exist
+        USER=vdr
+        GROUP=vdr
+        if ! getent group | grep -q "^$GROUP:" ; then
+                echo -n "Adding group $GROUP.."
+                addgroup --quiet --system $GROUP
+                echo "..done"
+        fi
+        if ! getent passwd | grep -q "^$USER:"; then
+                echo -n "Adding user $USER.."
+                adduser --system --home /var/lib/vdr --shell /bin/false \
+                        --gecos "VDR user" --no-create-home \
+                        --disabled-login --disabled-password \
+                        --ingroup $GROUP \
+                        $USER
+                echo "...done"
+        fi
 
-    # ensure that vdr's config and recording files are correctly owned
-    [ -e /var/lib/video ] && chown -R $USER:$GROUP /var/lib/video/
-    [ -e /var/lib/video.00 ] && chown -R $USER:$GROUP /var/lib/video.00/
-    [ -e /var/lib/video.01 ] && chown -R $USER:$GROUP /var/lib/video.01/
-    if [ -e /var/lib/vdr ] ; then
-        chown -R $USER:$GROUP /var/lib/vdr
-        chown $USER:$GROUP /var/lib/vdr/* > /dev/null 2>&1 || true
-    fi
-    if [ -e /var/cache/vdr ] ; then
-        chown $USER:$GROUP /var/cache/vdr
-        chown $USER:$GROUP /var/cache/vdr/* > /dev/null 2>&1|| true
-    fi
+        # put vdr in group video so that it can access the DVB device nodes
+        adduser $USER video > /dev/null || true
 
-    # make /usr/lib/vdr/vdr-shutdown.wrapper setuid/setgid (owner root:vdr, mode 6750)
-    if [ -e /usr/lib/vdr/vdr-shutdown.wrapper ] ; then
-        chown root:$GROUP /usr/lib/vdr/vdr-shutdown.wrapper && \
-        chmod a=,u+srwx,g+srx /usr/lib/vdr/vdr-shutdown.wrapper
-    fi
+        # ensure that vdr's config and recording files are correctly owned
+        [ -e /var/lib/video ] && chown -R $USER:$GROUP /var/lib/video/
+        if [ -e /var/lib/vdr ] ; then 
+            chown $USER:$GROUP /var/lib/vdr
+            chown $USER:$GROUP /var/lib/vdr/* > /dev/null 2>&1 || true
+        fi
+        if [ -e /var/cache/vdr ] ; then
+            chown $USER:$GROUP /var/cache/vdr
+            chown $USER:$GROUP /var/cache/vdr/* > /dev/null 2>&1|| true
+        fi
 
-    # make /usr/lib/vdr/ctvdrwrapper setuid/setgid
-    if [ -e /usr/lib/vdr/ctvdrwrapper ] ; then
-        chown root:$GROUP /usr/lib/vdr/ctvdrwrapper && \
-        chmod a=,u+srwx,g+srx /usr/lib/vdr/ctvdrwrapper
-    fi
-fi
+        # make /usr/lib/vdr/vdr-shutdown.wrapper setuid/setgid
+        # (owner root:vdr, mode 6750)
+        if [ -e /usr/lib/vdr/vdr-shutdown.wrapper ] ; then
+            chown root:$GROUP /usr/lib/vdr/vdr-shutdown.wrapper && \
+            chmod 6750 /usr/lib/vdr/vdr-shutdown.wrapper
+        fi
+
+        # Dropped alternatives from old package version
+        # (This can be dropped at squeeze +2)
+        update-alternatives --remove vdr /usr/bin/vdr-daemon
+        update-alternatives --remove vdr /usr/bin/vdr-kbd
+        update-alternatives --remove vdr /usr/bin/vdr-lirc
+        update-alternatives --remove vdr /usr/bin/vdr-rcu
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+db_stop
+
+
+# FIXME
+# wait for vdr to properly shutdown before it is restarted again
+sleep 5
+
 
 #DEBHELPER#
 
